<?php

namespace AppBundle\Repository;

/**
 * CountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountRepository extends \Doctrine\ORM\EntityRepository
{
}
