<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Search extends \AppBundle\Entity\Search implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'user', 'name', 'category', 'subcategory', 'jobType', 'budget', 'location', 'clientHistory', 'keywordSearchInAny', 'keywordSearchInTitle', 'keywordSearchInDescription', 'stopWordsInAny', 'stopWordsInTitle', 'stopWordsInDescription', 'skills', 'verifiedPayment', 'moneySpent', 'clientPreferredHoursOfExperience', 'clientPreferredFreelancerLocation', 'clientEnglishLevelPreference', 'clientTimezone', 'charsInDescription', 'clientFeedbackScore', 'experienceLevel', 'filterJobType', 'filterBudget', 'filterExperienceLevel', 'filterClientHistory', 'filterMoneySpent', 'filterSkills', 'filterVerifiedPayment', 'filterClientFeedbackScore', 'filterAvgRate', 'filterHoursBilled', 'filterClientTimezone', 'filterStars', 'action', 'filterLocation', 'createdAt', 'updatedAt'];
        }

        return ['__isInitialized__', 'id', 'user', 'name', 'category', 'subcategory', 'jobType', 'budget', 'location', 'clientHistory', 'keywordSearchInAny', 'keywordSearchInTitle', 'keywordSearchInDescription', 'stopWordsInAny', 'stopWordsInTitle', 'stopWordsInDescription', 'skills', 'verifiedPayment', 'moneySpent', 'clientPreferredHoursOfExperience', 'clientPreferredFreelancerLocation', 'clientEnglishLevelPreference', 'clientTimezone', 'charsInDescription', 'clientFeedbackScore', 'experienceLevel', 'filterJobType', 'filterBudget', 'filterExperienceLevel', 'filterClientHistory', 'filterMoneySpent', 'filterSkills', 'filterVerifiedPayment', 'filterClientFeedbackScore', 'filterAvgRate', 'filterHoursBilled', 'filterClientTimezone', 'filterStars', 'action', 'filterLocation', 'createdAt', 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Search $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterLocation', []);

        return parent::getFilterLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterLocation($filterLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterLocation', [$filterLocation]);

        return parent::setFilterLocation($filterLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', []);

        return parent::getAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction($action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', [$action]);

        return parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterStars()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterStars', []);

        return parent::getFilterStars();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterStars($filterStars)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterStars', [$filterStars]);

        return parent::setFilterStars($filterStars);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterClientTimezone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterClientTimezone', []);

        return parent::getFilterClientTimezone();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterClientTimezone($filterClientTimezone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterClientTimezone', [$filterClientTimezone]);

        return parent::setFilterClientTimezone($filterClientTimezone);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterHoursBilled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterHoursBilled', []);

        return parent::getFilterHoursBilled();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterHoursBilled($filterHoursBilled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterHoursBilled', [$filterHoursBilled]);

        return parent::setFilterHoursBilled($filterHoursBilled);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterAvgRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterAvgRate', []);

        return parent::getFilterAvgRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterAvgRate($filterAvgRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterAvgRate', [$filterAvgRate]);

        return parent::setFilterAvgRate($filterAvgRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterClientFeedbackScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterClientFeedbackScore', []);

        return parent::getFilterClientFeedbackScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterClientFeedbackScore($filterClientFeedbackScore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterClientFeedbackScore', [$filterClientFeedbackScore]);

        return parent::setFilterClientFeedbackScore($filterClientFeedbackScore);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterVerifiedPayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterVerifiedPayment', []);

        return parent::getFilterVerifiedPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterVerifiedPayment($filterVerifiedPayment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterVerifiedPayment', [$filterVerifiedPayment]);

        return parent::setFilterVerifiedPayment($filterVerifiedPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterSkills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterSkills', []);

        return parent::getFilterSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterSkills($filterSkills)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterSkills', [$filterSkills]);

        return parent::setFilterSkills($filterSkills);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterMoneySpent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterMoneySpent', []);

        return parent::getFilterMoneySpent();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterMoneySpent($filterMoneySpent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterMoneySpent', [$filterMoneySpent]);

        return parent::setFilterMoneySpent($filterMoneySpent);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterExperienceLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterExperienceLevel', []);

        return parent::getFilterExperienceLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterExperienceLevel($filterExperienceLevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterExperienceLevel', [$filterExperienceLevel]);

        return parent::setFilterExperienceLevel($filterExperienceLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterClientHistory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterClientHistory', []);

        return parent::getFilterClientHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterClientHistory($filterClientHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterClientHistory', [$filterClientHistory]);

        return parent::setFilterClientHistory($filterClientHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterBudget()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterBudget', []);

        return parent::getFilterBudget();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterBudget($filterBudget)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterBudget', [$filterBudget]);

        return parent::setFilterBudget($filterBudget);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterJobType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterJobType', []);

        return parent::getFilterJobType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterJobType($filterJobType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterJobType', [$filterJobType]);

        return parent::setFilterJobType($filterJobType);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubcategory($subcategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubcategory', [$subcategory]);

        return parent::setSubcategory($subcategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubcategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubcategory', []);

        return parent::getSubcategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobType($jobType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobType', [$jobType]);

        return parent::setJobType($jobType);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobType', []);

        return parent::getJobType();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudget($budget)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudget', [$budget]);

        return parent::setBudget($budget);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudget()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudget', []);

        return parent::getBudget();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientHistory($clientHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientHistory', [$clientHistory]);

        return parent::setClientHistory($clientHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientHistory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientHistory', []);

        return parent::getClientHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywordSearchInAny($keywordSearchInAny)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywordSearchInAny', [$keywordSearchInAny]);

        return parent::setKeywordSearchInAny($keywordSearchInAny);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywordSearchInAny()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywordSearchInAny', []);

        return parent::getKeywordSearchInAny();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywordSearchInTitle($keywordSearchInTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywordSearchInTitle', [$keywordSearchInTitle]);

        return parent::setKeywordSearchInTitle($keywordSearchInTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywordSearchInTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywordSearchInTitle', []);

        return parent::getKeywordSearchInTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywordSearchInDescription($keywordSearchInDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywordSearchInDescription', [$keywordSearchInDescription]);

        return parent::setKeywordSearchInDescription($keywordSearchInDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywordSearchInDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywordSearchInDescription', []);

        return parent::getKeywordSearchInDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setStopWordsInAny($stopWordsInAny)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStopWordsInAny', [$stopWordsInAny]);

        return parent::setStopWordsInAny($stopWordsInAny);
    }

    /**
     * {@inheritDoc}
     */
    public function getStopWordsInAny()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStopWordsInAny', []);

        return parent::getStopWordsInAny();
    }

    /**
     * {@inheritDoc}
     */
    public function setStopWordsInTitle($stopWordsInTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStopWordsInTitle', [$stopWordsInTitle]);

        return parent::setStopWordsInTitle($stopWordsInTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getStopWordsInTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStopWordsInTitle', []);

        return parent::getStopWordsInTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setStopWordsInDescription($stopWordsInDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStopWordsInDescription', [$stopWordsInDescription]);

        return parent::setStopWordsInDescription($stopWordsInDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getStopWordsInDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStopWordsInDescription', []);

        return parent::getStopWordsInDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSkills($skills)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSkills', [$skills]);

        return parent::setSkills($skills);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkills', []);

        return parent::getSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerifiedPayment($verifiedPayment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerifiedPayment', [$verifiedPayment]);

        return parent::setVerifiedPayment($verifiedPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerifiedPayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerifiedPayment', []);

        return parent::getVerifiedPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneySpent($moneySpent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneySpent', [$moneySpent]);

        return parent::setMoneySpent($moneySpent);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneySpent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneySpent', []);

        return parent::getMoneySpent();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientPreferredHoursOfExperience($clientPreferredHoursOfExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientPreferredHoursOfExperience', [$clientPreferredHoursOfExperience]);

        return parent::setClientPreferredHoursOfExperience($clientPreferredHoursOfExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientPreferredHoursOfExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientPreferredHoursOfExperience', []);

        return parent::getClientPreferredHoursOfExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientPreferredFreelancerLocation($clientPreferredFreelancerLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientPreferredFreelancerLocation', [$clientPreferredFreelancerLocation]);

        return parent::setClientPreferredFreelancerLocation($clientPreferredFreelancerLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientPreferredFreelancerLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientPreferredFreelancerLocation', []);

        return parent::getClientPreferredFreelancerLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientEnglishLevelPreference($clientEnglishLevelPreference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientEnglishLevelPreference', [$clientEnglishLevelPreference]);

        return parent::setClientEnglishLevelPreference($clientEnglishLevelPreference);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientEnglishLevelPreference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientEnglishLevelPreference', []);

        return parent::getClientEnglishLevelPreference();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientTimezone($clientTimezone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientTimezone', [$clientTimezone]);

        return parent::setClientTimezone($clientTimezone);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientTimezone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientTimezone', []);

        return parent::getClientTimezone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharsInDescription($charsInDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharsInDescription', [$charsInDescription]);

        return parent::setCharsInDescription($charsInDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharsInDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharsInDescription', []);

        return parent::getCharsInDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientFeedbackScore($clientFeedbackScore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientFeedbackScore', [$clientFeedbackScore]);

        return parent::setClientFeedbackScore($clientFeedbackScore);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientFeedbackScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientFeedbackScore', []);

        return parent::getClientFeedbackScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setExperienceLevel($experienceLevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperienceLevel', [$experienceLevel]);

        return parent::setExperienceLevel($experienceLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperienceLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperienceLevel', []);

        return parent::getExperienceLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setResult($result)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResult', [$result]);

        return parent::setResult($result);
    }

    /**
     * {@inheritDoc}
     */
    public function getResult()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResult', []);

        return parent::getResult();
    }

}
